### ISSUE TITLE
Unable to upload images when commenting/voting on a vault-contribution

### ISSUE THREAD

**Issue by DjedMaroz** [vault-lexicon/issues#7]
<img width="2087" height="752" alt="Image" src="https://github.com/user-attachments/assets/3dea6478-3c9b-466e-80d5-cd1465347132" />

Encountering issues with uploading pictures on comments to contributions on the vault. Tested/verified with Mozilla Firefox and Google Chrome in the latest installment.

**Comment by nelak2** [comment]
@DjedMaroz This should be working now but so I can double check - what was the project you were trying to comment on? Also - could you give it a try?

**Comment by DjedMaroz** [comment]
<img width="2040" height="1027" alt="Image" src="https://github.com/user-attachments/assets/9bea1139-782e-4630-8eca-cad5ab66bc0a" />

The issue is still present as of now when I tried to edit my comment at the NWN2 campaign "Isle of Shrines" to contain pictures: https://neverwintervault.org/project/nwn2/module/isle-shrines

I also added a new comment to this module and could not add a picture as well (in case there was a difference between editing a post and posting a new one): https://neverwintervault.org/project/nwn2/module/rethilds-wizard

**Comment by nelak2** [comment]
I was able to recreate it now. Looks like the issue is specific to certain user accounts.

**Comment by nelak2** [comment]
@DjedMaroz Okay. I was able to resolve it for my user account. Could you try it again?

**Comment by DjedMaroz** [comment]
It worked for me.
